services:
  mongo:
    environment:
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_ROOT_USERNAME: root
    image: mongo:4.4
    volumes:
    - /home/albert0i/sandbox/LearnDockerNodeExpress/data/db:/data/db:rw

  nginx:
    depends_on:
    - node-app
    image: nginx:stable-alpine
    ports:
    - 3000:80/tcp
    volumes:
    - /home/albert0i/sandbox/LearnDockerNodeExpress/nginx/default.conf:/etc/nginx/conf.d/default.conf:rw

  node-app:
    build:
      args:
        NODE_ENV: development
      context: /home/albert0i/sandbox/LearnDockerNodeExpress
    command: npm run dev
    depends_on:
    - mongo
    - redis
    environment:
      MONGO_PASSWORD: root
      MONGO_USER: root
      NODE_ENV: development
      PORT: '3000'
      SESSION_SECRET: secret
    volumes:
    - /home/albert0i/sandbox/LearnDockerNodeExpress:/app:rw
    - /app/node_modules

  redis:
    image: redis:6.2.6
version: '3.0'
