version: "3"
services:
  nginx:
    ports:
      - "80:80"

  node-app:

    deploy:
      replicas: 3
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        delay: 15s

 #   build:
 #     context: . 
 #     args: 
 #       NODE_ENV: production
    environment:
      - NODE_ENV=production
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - SESSION_SECRET=${SESSION_SECRET}
    command: npm run start 

  mongo:
      environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

#
# Swarm commands:
#   docker stack deploy -c docker-compose.yml -c docker-compose.prod.yml myapp
#   docker node ls
#   docker stack ls 
#   docker stack service myapp
#   docker ps
#   docker service ls
#   docker stack ps myapp 
#   

#
# [v1.25.0] "Only pull images that can't be built" should be optional #7103
# https://github.com/docker/compose/issues/7103
# 
# It seems to be due to the Only pull images that can't be built feature of v1.25.0 (v1.24.1 doesn't have this issue).
# yep, confirmed. 1.25.1-rc1 solves the issue. Waiting for stable release 
#
# So, if you want to use docker-compose pull node-app in production environment, 
# be sure to COMMENT OUT line 8~11.
# 
# EOF (2022/04/30)
#