services:
  mongo:
    environment:
      MONGO_INITDB_ROOT_PASSWORD: ''
      MONGO_INITDB_ROOT_USERNAME: ''
    image: mongo:4.4
    volumes:
    - /home/albert0i/sandbox/LearnDockerNodeExpress/data/db:/data/db:rw
  nginx:
    depends_on:
    - node-app
    image: nginx:stable-alpine
    ports:
    - 80:80/tcp
    volumes:
    - /home/albert0i/sandbox/LearnDockerNodeExpress/nginx/default.conf:/etc/nginx/conf.d/default.conf:rw
  node-app:
    command: npm run start
    depends_on:
    - mongo
    - redis
    environment:
      MONGO_PASSWORD: ''
      MONGO_USER: ''
      NODE_ENV: production
      PORT: '3000'
      SESSION_SECRET: ''
    image: albert0i/node-app
  redis:
    image: redis:6.2.6
version: '3.0'

